### ISSUE TITLE
The given data failed to pass validation.

### ISSUE THREAD

**Issue by Casperhr** [nodes-php/core#31]
We need to make sure validation errors from form requests are not getting into bugsnag
Can we change the exceptions to have dontReport() on?

throw new ValidationException($validator, $this->response($this->formatErrors($validator)));

**Comment by Skyback** [comment]
@Casperhr @rtrzebinski  I've been investigating the issue. By default, our ValidationException exception should not report to bugsnag. But our validation exception will only be thrown in case the request is an API call. If it's not, then the Illuminate ValidationException will be thrown (which will trigger the redirect back behaviour that's not present on Nodes ValidationException).

```
protected function failedValidation(Validator $validator)
    {
        if ($this->isApiRequest()) {
            throw new ValidationException($validator, $this->getErrorCodes());
        }

        parent::failedValidation($validator);
    }
```

One quick solution would be to add the Illuminate ValidationException to the $dontReport array on the default exception handler (app/Exceptions/Handler.php).

```
    protected $dontReport = [
        AuthorizationException::class,
        HttpException::class,
        ModelNotFoundException::class,
        ValidationException::class,   <---- Here
    ];
```

Otherwise, I'll need to take a deeper look into this and see the less hacky way of changing this behaviour.

**Comment by Casperhr** [comment]
We can add it to the bugsnag handler and the nodes-api handler

Else we should add it to the project start guide, which is just growing :(

@Skyback

**Comment by Skyback** [comment]
We don't need to add it to nodes-api handler because API calls will trigger Nodes ValidationException which, by default, does not report to Bugsnag. 

I guess the best solution would be to add it to bugsnag handler. We can also create a custom array on bugsnag handler to ignore some other exceptions like TokenMismatchException.

Agree?

@Casperhr

**Comment by Casperhr** [comment]
Sounds good

Give it a go!

**Comment by Casperhr** [comment]
But I really think TokenMissMatch have to be solved in the handler. We can't show whoops errors for that

**Comment by Casperhr** [comment]
@Skyback did you add this to the installation guides?

**Comment by Skyback** [comment]
@Casperhr Will add it now.

**Comment by Skyback** [comment]
https://github.com/nodes-php/core/commit/7d0c79d164cb459646c27866e851448f7ef0195c
